# Generated by Django 3.1.7 on 2021-03-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='entry',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
