version: '3.7'
services:
  postgres:
    container_name: to-do-postgres
    image: postgres:15.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todo
      - POSTGRES_PASSWORD=pwd
