version: '3.7'

services:

  postgres_service:
    container_name: 'todo_pg_container'
    image: 'postgres:15.2'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=todo_user
      - POSTGRES_PASSWORD=todo_password
      - POSTGRES_DB=todo_db
