install-nodejs:
	sudo apt install nodejs

# npx is required, but npx comes with npm
install-npm:
	sudo apt install npm

create-react-app:
	npx create-react-app my-app

start-react-app:
	cd my-app && \
		npm start
