version: '3.7'

services:
  db:
    image: postgres
    # restart: always
    environment:
      # - DATABASE_URL=127.0.0.1
      - POSTGRES_PASSWORD=letmein
      - POSTGRES_DB=test_database
    ports:
      - 5432:5432
    #   - DATABASE_URL=value